excerpt_separator:"."
pygments:true
markdown:kramdown
url:http://kristianvea.github.io
title:Kristian Vea
tagline:Om politikk, samfunn og arkitektur
description:Om politikk, samfunn og arkitektur
paginate:5
