excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kristianvea.github.io
title: Kristian Vea
tagline: Om politikk, samfunn og arkitektur
description: Kristian Vea er folkevalgt for Miljøpartiet De Grønne på Grünerløkka i Oslo.
paginate: 5